### ISSUE TITLE
Impliment UTF-8

### ISSUE THREAD

**Issue by yocke** [HostiFi/Export-UniFi-Devices-to-CSV#1]
Is it possible to impliment UTF-8 enconding to the export?
In the output on the server it looks correct but the csv does gives some funny text, like the one below.

Kv SlÃ¤ndan

The correct text here should be, Kv Sländan

**Comment by reillychase** [comment]
Hi @yocke! I was not able to reproduce this issue. I renamed one of my devices to Kv Sländan, then ran the script, opened the CSV in Google Sheets and it displayed correctly.

Are you using Python3?
Does it display correctly if you open the CSV in Google Sheets?

**Comment by yocke** [comment]
Hi @reillychase!

Works as expected in Sheets but not in Excel. Funny thing.
Uploaded the file and then downloaded it again as xlsx and it all looks good.
Thanks for the quick testing.
Much appreciated!
