### ISSUE TITLE
MongoClient not found on Controller 8.1 

### ISSUE THREAD

**Issue by abarzyk-SMB** [HostiFi/Export-UniFi-Devices-to-CSV#3]
sudo python3 ./unifi_devices_to_csv.py
Traceback (most recent call last):
  File "./unifi_devices_to_csv.py", line 2, in <module>
    from pymongo import MongoClient
ModuleNotFoundError: No module named 'pymongo'

**Comment by reillychase** [comment]
Try `pip3 install pymongo` then run the script again

Also you might want to give our website version of this script a try instead too https://export.hostifi.com

**Comment by abarzyk-SMB** [comment]
That did it. Sencere thanks as I was going down the rabbit hole!

**Comment by reillychase** [comment]
No problem!
